### First Route
GET http://localhost:5000/hello

### First Route POST
POST http://localhost:5000/hello
Content-Type: application/json

{
    "name": "Satogo"
}

### GET All Users
GET http://localhost:5000/api/v1/user